environment:
  matrix:
    - PYTHON: "C:\\PYTHON36"
    - PYTHON: "C:\\PYTHON37"
    - PYTHON: "C:\\PYTHON38"
    - PYTHON: "C:\\PYTHON39"
install:
  - "%PYTHON%\\python.exe -m pip install codecov coverage nose mock pynput"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m nose --with-coverage --cover-xml"
after_test:
  - "%PYTHON%\\Scripts\\codecov.exe -f coverage.xml"
